name: Daily workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-daily-tests:
    uses: ./.github/workflows/testing_dev.yml

  notify:
    runs-on: ubuntu-latest
    needs: [run-daily-tests]
    if: failure()
    steps:
    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465  # TSL
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: van der Meer Lab to BIDS Daily Failure
        to: cody.c.baker.phd@gmail.com
        from: van der Meer Lab to BIDS
        body: "The daily workflow for van der Meer Lab to BIDS failed: please check status at https://github.com/con/vandermeerlab-to-bids/actions/workflows/dailies.yml"
