name: Dev tests
on:
  workflow_call:

jobs:
  run:
    # Will read on PR dashboard as 'Deploy / DevTests / {python-version} on {os}'
    # Action dashboard identified by 'Dev tests'
    # Requirement settings identified as 'DevTests / Python {python-version} on {os}'
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]  # Keep this in the form of a matrix to easily add future versions
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Global Setup
        run: |
          python -m pip install -U pip  # Official recommended way
          pip install pytest-xdist

      - name: Install minimal package
        run: pip install .

      - name: Test import
        run: python -c "import vandermeerlab_to_bids"
